title = "Colton Provias"

[params]
dateFormat = "2006-01-02"

[params.author]
name = "Colton Provias"
headline = "Software Engineer, Audio Engineer, Musician"
bio = "Senior Software Engineer at Google and musician."
links = [
    { linkedin = "https://linkedin.com/in/ColtonProvias" },
    { bluesky = "https://bsky.app/profile/cprovias.bsky.social" },
    { mastodon = "https://universeodon.com/@cprovias" }
]
